hist_dict = {"Jpsi_MC_mee": {"plot_label": "$B \\rightarrow KJ/\\psi$",
                             "bin_width": 32,
                             "num_bins": 50,
                             "x_min": 2200,
                             "x_max": 3800,
                             "x_label": "M(ee), MeV",
                             "y_label": "Events/32 MeV",
                             "x_var": "J_psi_1S_M"},
             "data_mee": {"plot_label": "$B \\rightarrow Kee$",
                          "bin_width": 32,
                          "num_bins": 50,
                          "x_min": 2200,
                          "x_max": 3800,
                          "x_label": "M(ee), MeV",
                          "y_label": "Events/32 MeV",
                          "x_var": "J_psi_1S_M"},
             "Jpsi_MC_mKee": {},
             "data_mKee": {}}
