initial_params_dict = {
    "brem_PZ": {
        "brem_zero": {'mu': 3100., 'sigma': 21., 'alphal': 0.2, 'nl': 3.5, 'alphar': 3.0, 'nr': 3.5},
        "brem_one": {'mu': 700., 'sigma': 500., 'alphal': 0.23, 'nl': 3.5, 'alphar': 0.5, 'nr': 10.},
        "brem_two": {'mu': 3100., 'sigma': 42., 'alphal': 0.7, 'nl': 3.5, 'alphar': 0.3, 'nr': 3.5}},

    "brem_PE": {
        "brem_zero": {'mu': 3100., 'sigma': 21., 'alphal': 0.2, 'nl': 3.5, 'alphar': 3.0, 'nr': 3.5},
        "brem_one": {'mu': 700., 'sigma': 500., 'alphal': 0.23, 'nl': 3.5, 'alphar': 0.5, 'nr': 10.},
        "brem_two": {'mu': 3100., 'sigma': 42., 'alphal': 0.7, 'nl': 3.5, 'alphar': 0.3, 'nr': 3.5}},

    "brem_PX": {
        "brem_zero": {'mu': 3100., 'sigma': 21., 'alphal': 0.2, 'nl': 3.5, 'alphar': 3.0, 'nr': 3.5},
        "brem_one": {'mu': 0., 'sigma': 1000., 'alphal': 0.23, 'nl': 3.5, 'alphar': 0.5, 'nr': 10.},
        "brem_two": {'mu': 3100., 'sigma': 42., 'alphal': 0.7, 'nl': 3.5, 'alphar': 0.3, 'nr': 3.5}},

    "brem_PY": {
        "brem_zero": {'mu': 3100., 'sigma': 21., 'alphal': 0.2, 'nl': 3.5, 'alphar': 3.0, 'nr': 3.5},
        "brem_one": {'mu': 0., 'sigma': 1000., 'alphal': 0.23, 'nl': 3.5, 'alphar': 0.5, 'nr': 10.},
        "brem_two": {'mu': 3100., 'sigma': 42., 'alphal': 0.7, 'nl': 3.5, 'alphar': 0.3, 'nr': 3.5}},

    "TRACK_PE": {
        "brem_zero": {'mu': 5250., 'sigma': 30., 'alphal': 0.2, 'nl': 50., 'alphar': 3.0, 'nr': 3.5},
        "brem_one": {'mu': 5., 'sigma': 5., 'theta': 10000.},
        "brem_two": {'mu': 5300., 'sigma': 40., 'alphal': 0.4, 'nl': 24., 'alphar': 0.9, 'nr': 3.}},

    "TRACK_P": {
        "brem_zero": {'mu': 5250., 'sigma': 30., 'alphal': 0.2, 'nl': 50., 'alphar': 3.0, 'nr': 3.5},
        "brem_one": {'mu': 5., 'sigma': 5., 'theta': 10000.},
        "brem_two": {'mu': 5300., 'sigma': 40., 'alphal': 0.4, 'nl': 24., 'alphar': 0.9, 'nr': 3.}},

    "TRACK_PX": {
        "brem_zero": {'mu': 5250., 'sigma': 30., 'alphal': 0.2, 'nl': 50., 'alphar': 3.0, 'nr': 3.5},
        "brem_one": {'mu': 3550., 'sigma': 2000., 'alphal': 1.2, 'nl': 5., 'alphar': 1.0, 'nr': 3.5},
        "brem_two": {'mu': 5300., 'sigma': 40., 'alphal': 1.4, 'nl': 24., 'alphar': 0.9, 'nr': 3.}},

    "TRACK_PY": {
        "brem_zero": {'mu': 5250., 'sigma': 30., 'alphal': 0.2, 'nl': 50., 'alphar': 3.0, 'nr': 3.5},
        "brem_one": {'mu': 5250., 'sigma': 500., 'alphal': 0.2, 'nl': 5., 'alphar': 3.0, 'nr': 3.5},
        "brem_two": {'mu': 5300., 'sigma': 40., 'alphal': 0.4, 'nl': 24., 'alphar': 0.9, 'nr': 3.}}
}

data_branches = ["J_psi_1S_M", "B_plus_M", "B_plus_DTFM_M", "BDT_score_selection", "e_plus_BremMultiplicity",
                 "e_minus_BremMultiplicity", "L0TISOnly_d", "L0ETOSOnly_d",
                 'e_plus_L0Calo_ECAL_realET', 'e_minus_L0Calo_ECAL_realET', 'TCKCat', 'e_minus_L0ElectronDecision_TOS',
                 'B_plus_L0Global_TIS', 'e_plus_L0ElectronDecision_TOS', 'e_plus_L0Calo_ECAL_realET',
                 'e_minus_L0Calo_ECAL_realET', 'TCKCat', 'e_plus_L0ElectronDecision_TOS', 'B_plus_L0Global_TIS',
                 'e_minus_L0ElectronDecision_TOS', 'e_plus_TRACK_PY', 'e_plus_TRACK_PX',
                 'e_plus_TRACK_P', 'e_plus_TRACK_PZ', 'e_minus_TRACK_PY', 'e_minus_TRACK_PX',
                 'e_minus_TRACK_P', 'e_minus_TRACK_PZ', 'e_plus_PX',
                 'e_plus_PE', 'e_plus_PZ', 'e_minus_PY', 'e_minus_PX',
                 'e_minus_PE', 'e_minus_PZ', 'e_plus_PY']

mc_branches = ["J_psi_1S_M", "B_plus_M", "B_plus_DTFM_M", "BDT_score_selection", "J_psi_1S_M_TRUE",
               "e_plus_BremMultiplicity", "e_minus_BremMultiplicity", "L0TISOnly_d", "L0ETOSOnly_d",
               'e_plus_L0Calo_ECAL_realET', 'e_minus_L0Calo_ECAL_realET', 'TCKCat', 'e_minus_L0ElectronDecision_TOS',
               'B_plus_L0Global_TIS', 'e_plus_L0ElectronDecision_TOS', 'e_plus_L0Calo_ECAL_realET',
               'e_minus_L0Calo_ECAL_realET', 'TCKCat', 'e_plus_L0ElectronDecision_TOS', 'B_plus_L0Global_TIS',
               'e_minus_L0ElectronDecision_TOS',
               'e_plus_TRACK_PY', 'e_plus_TRACK_PX',
               'e_plus_TRACK_P', 'e_plus_TRACK_PZ', 'e_minus_TRACK_PY', 'e_minus_TRACK_PX',
               'e_minus_TRACK_P', 'e_minus_TRACK_PZ', 'e_plus_PX',
               'e_plus_PE', 'e_plus_PZ', 'e_minus_PY', 'e_minus_PX',
               'e_minus_PE', 'e_minus_PZ', "e_plus_PY"]

hist_dict = {"Jpsi_MC_brem_PZ": {"plot_label": "$B \\rightarrow KJ/\\psi$",
                                 "bin_width": 1000,
                                 "num_bins": 60,
                                 "x_min": 0,
                                 "x_max": 60000,
                                 "x_label": "Brem PZ, MeV",
                                 "y_label": "Events/1 GeV",
                                 "x_var": "brem_PZ"},
             "data_brem_PZ": {"plot_label": "$B \\rightarrow Kee$",
                              "bin_width": 1000,
                              "num_bins": 60,
                              "x_min": 0,
                              "x_max": 60000,
                              "x_label": "Brem PZ, MeV",
                              "y_label": "Events/1 GeV",
                              "x_var": "brem_PZ"},
             "Jpsi_MC_brem_PE": {"plot_label": "$B \\rightarrow KJ/\\psi$",
                                 "bin_width": 1000,
                                 "num_bins": 60,
                                 "x_min": 0,
                                 "x_max": 60000,
                                 "x_label": "Brem P, MeV",
                                 "y_label": "Events/1 GeV",
                                 "x_var": "brem_P"},
             "data_brem_PE": {"plot_label": "$B \\rightarrow Kee$",
                              "bin_width": 1000,
                              "num_bins": 60,
                              "x_min": 0,
                              "x_max": 60000,
                              "x_label": "Brem P, MeV",
                              "y_label": "Events/1 GeV",
                              "x_var": "brem_P"},
             "Jpsi_MC_brem_PX": {"plot_label": "$B \\rightarrow KJ/\\psi$",
                                 "bin_width": 200,
                                 "num_bins": 50,
                                 "x_min": -5000,
                                 "x_max": 5000,
                                 "x_label": "Brem PX, MeV",
                                 "y_label": "Events/200 MeV",
                                 "x_var": "brem_PX"},
             "data_brem_PX": {"plot_label": "$B \\rightarrow Kee$",
                              "bin_width": 200,
                              "num_bins": 50,
                              "x_min": -5000,
                              "x_max": 5000,
                              "x_label": "Brem PX, MeV",
                              "y_label": "Events/200 MeV",
                              "x_var": "brem_PX"},
             "Jpsi_MC_brem_PY": {"plot_label": "$B \\rightarrow KJ/\\psi$",
                                 "bin_width": 200,
                                 "num_bins": 50,
                                 "x_min": -5000,
                                 "x_max": 5000,
                                 "x_label": "Brem PY, MeV",
                                 "y_label": "Events/200 MeV",
                                 "x_var": "brem_PY"},
             "data_brem_PY": {"plot_label": "$B \\rightarrow Kee$",
                              "bin_width": 200,
                              "num_bins": 50,
                              "x_min": -5000,
                              "x_max": 5000,
                              "x_label": "Brem PY, MeV",
                              "y_label": "Events/200 MeV",
                              "x_var": "brem_PY"},
             "data_TRACK_P": {"plot_label": "$B \\rightarrow Kee$",
                              "bin_width": 4000,
                              "num_bins": 60,
                              "x_min": 10000,
                              "x_max": 250000,
                              "x_label": "Track P, MeV",
                              "y_label": "Events/4 GeV",
                              "x_var": "TRACK_P"},
             "Jpsi_MC_TRACK_P": {"plot_label": "$B \\rightarrow KJ/\\psi$",
                                 "bin_width": 4000,
                                 "num_bins": 60,
                                 "x_min": 10000,
                                 "x_max": 250000,
                                 "x_label": "Track P, MeV",
                                 "y_label": "Events/4 GeV",
                                 "x_var": "TRACK_P"},
             "data_TRACK_PE": {"plot_label": "$B \\rightarrow Kee$",
                               "bin_width": 4000,
                               "num_bins": 60,
                               "x_min": 10000,
                               "x_max": 250000,
                               "x_label": "Track PZ, MeV",
                               "y_label": "Events/4 GeV",
                               "x_var": "TRACK_PZ"},
             "Jpsi_MC_TRACK_PE": {"plot_label": "$B \\rightarrow KJ/\\psi$",
                                  "bin_width": 4000,
                                  "num_bins": 60,
                                  "x_min": 10000,
                                  "x_max": 250000,
                                  "x_label": "Track PZ, MeV",
                                  "y_label": "Events/4 GeV",
                                  "x_var": "TRACK_PZ"},
             "data_TRACK_PX": {"plot_label": "$B \\rightarrow Kee$",
                               "bin_width": 500,
                               "num_bins": 80,
                               "x_min": -20000,
                               "x_max": 20000,
                               "x_label": "Track PX, MeV",
                               "y_label": "Events/.5 GeV",
                               "x_var": "TRACK_PX"},
             "Jpsi_MC_TRACK_PX": {"plot_label": "$B \\rightarrow KJ/\\psi$",
                                  "bin_width": 500,
                                  "num_bins": 80,
                                  "x_min": -20000,
                                  "x_max": 20000,
                                  "x_label": "Track PX, MeV",
                                  "y_label": "Events/.5 GeV",
                                  "x_var": "TRACK_PX"},
             "data_TRACK_PY": {"plot_label": "$B \\rightarrow Kee$",
                               "bin_width": 500,
                               "num_bins": 80,
                               "x_min": -20000,
                               "x_max": 20000,
                               "x_label": "Track PX, MeV",
                               "y_label": "Events/.5 GeV",
                               "x_var": "TRACK_PY"},
             "Jpsi_MC_TRACK_PY": {"plot_label": "$B \\rightarrow KJ/\\psi$",
                                  "bin_width": 500,
                                  "num_bins": 80,
                                  "x_min": -20000,
                                  "x_max": 20000,
                                  "x_label": "Track PX, MeV",
                                  "y_label": "Events/.5 GeV",
                                  "x_var": "TRACK_PY"},
             "q2_nobrem": {"plot_label": "$B \\rightarrow KJ/\\psi$",
                           "bin_width": .2,
                           "num_bins": 70,
                           "x_min": 0.,
                           "x_max": 14.,
                           "x_label": "$q^2$ track, $GeV^2$",
                           "y_label": "Events/.2 $GeV^2$",
                           "x_var": "q2_nobrem"}
             }
